const data=Array.isArray(window.SUPPLIERS)?window.SUPPLIERS:[];
const drop=n=>{const i=data.findIndex(x=>x.name===n);if(i>=0)data.splice(i,1)};
drop("Gavino's Japanese Donuts");drop('Wonderbake');
const aab=data.find(x=>x.name==='All About Baking');if(aab){aab.location='52 stores in 24 Philippine cities. Quezon City branches include Congressional Avenue, Quezon Avenue, SM North EDSA, Eastwood, Robinsons Magnolia and SM Fairview.';aab.website='https://allaboutbaking.ph/pages/our-stores';aab.mapsQuery='All About Baking Philippines';aab.searchTerms=['Quezon City','Congressional Avenue','Quezon Avenue','SM North EDSA','Eastwood','Robinsons Magnolia','SM Fairview','all branches']}
const additions=[
{name:'Rise Artisanal',region:'Philippines',location:'Quezon City, Metro Manila',categories:['Bakery','Sourdough bread','Artisan bread','Workshops'],levels:['Beginner','Growing bakery'],bestFor:'Long-fermented sourdough, focaccia and hands-on learning',description:'A Quezon City microbakery producing naturally leavened bread, focaccia and seasonal baked goods, with practical sourdough workshops for home bakers.',website:'https://riseartisanal.com/',mapsQuery:'Rise Artisanal Quezon City',access:'Pre-order + workshops',featured:true},
{name:'Wonderbake',region:'Philippines',location:'Multiple branches. Use Google Maps to view all current Wonderbake locations.',categories:['Ingredients','Tools & bakeware','Packaging','Cake decorating'],levels:['Beginner','Growing bakery'],bestFor:'Accessible baking ingredients, tools, packaging and decorating supplies',description:'A multi-branch baking-supply retailer serving home and small-business bakers. The branch-wide Maps search keeps all current locations discoverable.',website:'https://www.facebook.com/wonderbakeph/',mapsQuery:'Wonderbake baking supplies Philippines',access:'Branches + public social page',searchTerms:['Quezon City','Metro Manila','all branches','branch locator']},
{name:"Gavino's Baking Essentials",region:'Philippines',location:'Visayas Avenue, Quezon City, Metro Manila',categories:['Ingredients','Tools & bakeware','Packaging','Cake decorating'],levels:['Beginner','Growing bakery','Professional'],bestFor:'Baking essentials, ingredients and tools along Visayas Avenue',description:'A Quezon City baking essentials store for ingredients, tools, packaging and everyday production needs. This is the baking-supply business, not the donut shop.',website:'https://www.google.com/search?q=Gavino%27s+Baking+Essentials+Visayas+Avenue+Quezon+City',mapsQuery:"Gavino's Baking Essentials Visayas Avenue Quezon City",access:'Physical store + public search',searchTerms:['Visayas Avenue','Quezon City','Project 6','baking supplies','baking essentials']},
{name:'The Bread Depot',region:'Philippines',location:'Online supplier serving bakers in the Philippines',categories:['Flour & grains','Professional ingredients','Sourdough supplies'],levels:['Beginner','Growing bakery','Professional'],bestFor:'Bread flour and regular online flour ordering',description:'An online flour supplier used by working bakers, including Rise Artisanal, for dependable bread-flour sourcing and bakery production needs.',website:'https://www.google.com/search?q=The+Bread+Depot+flour+supplier+Philippines',mapsQuery:'The Bread Depot flour supplier Philippines',access:'Online ordering',featured:true,searchTerms:['online flour','bread flour','sourdough flour','Philippines delivery']},
{name:'Kamuning Bakery Cafe',region:'Philippines',location:'43 Judge Jimenez Street corner K-1 Street, Kamuning, Quezon City',categories:['Bakery','Traditional bread','Pandesal','Cafe'],levels:['Beginner','Growing bakery','Professional'],bestFor:'Historic Filipino bread baked in a traditional pugon',description:'A historic Quezon City bakery best known for pandesal, pan de suelo and other breads made using its traditional wood-fired brick oven.',website:'https://www.google.com/search?q=Kamuning+Bakery+Cafe',mapsQuery:'Kamuning Bakery Cafe Quezon City',access:'Bakery + cafe'},
{name:'Pan de Manila',region:'Philippines',location:'Quezon City-based bakery chain with branches across Metro Manila and the Philippines',categories:['Bakery','Pandesal','Traditional bread','Spreads'],levels:['Beginner','Growing bakery'],bestFor:'Everyday Filipino breads, pandesal and take-home spreads',description:'A Philippine bakery chain founded in Quezon City, known for freshly baked pandesal, specialty breads, spreads and merienda products.',website:'https://www.google.com/search?q=Pan+de+Manila+Quezon+City',mapsQuery:'Pan de Manila Quezon City',access:'Branches + delivery platforms'}];
const names=new Set(data.map(x=>x.name.toLowerCase()));additions.forEach(x=>{if(!names.has(x.name.toLowerCase())){data.unshift(x);names.add(x.name.toLowerCase())}});
const suppliers=data,$=id=>document.getElementById(id),grid=$('supplier-grid'),search=$('search'),form=$('main-search-form'),region=$('region-filter'),category=$('category-filter'),level=$('level-filter'),count=$('results-count'),empty=$('empty-state'),clear=$('clear-filters');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const maps=q=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`;
const cats=[...new Set(suppliers.flatMap(x=>x.categories||[]))].sort();cats.forEach(c=>{const o=document.createElement('option');o.value=o.textContent=c;category.appendChild(o)});$('supplier-stat').textContent=suppliers.length;$('ph-stat').textContent=suppliers.filter(x=>x.region==='Philippines').length;$('category-stat').textContent=`${cats.length}+`;
const card=x=>`<article class="card ${x.featured?'featured':''}"><div class="card-top"><span class="region ${x.region==='International'?'international':''}">${esc(x.region)}</span>${x.featured?'<span class="featured-label">Strong first stop</span>':''}</div><h3>${esc(x.name)}</h3><p class="best-for">${esc(x.bestFor)}</p><p class="description">${esc(x.description)}</p><div class="meta"><div class="meta-row"><strong>Location</strong><span>${esc(x.location)}</span></div><div class="meta-row"><strong>Access</strong><span>${esc(x.access)}</span></div><div class="meta-row"><strong>Level</strong><span>${esc((x.levels||[]).join(' · '))}</span></div></div><div class="tags">${[...(x.categories||[]),...(x.levels||[])].map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div><div class="actions"><a class="btn primary" href="${esc(x.website)}" target="_blank" rel="noopener noreferrer">Visit listing ↗</a><a class="btn secondary" href="${maps(x.mapsQuery||x.name)}" target="_blank" rel="noopener noreferrer">Google Maps ↗</a></div></article>`;
function apply(){const q=search.value.trim().toLowerCase(),r=region.value,c=category.value,l=level.value;const filtered=suppliers.filter(x=>{const hay=[x.name,x.location,x.bestFor,x.description,x.access,...(x.searchTerms||[]),...(x.categories||[]),...(x.levels||[])].join(' ').toLowerCase();return(!q||hay.includes(q))&&(!r||x.region===r)&&(!c||(x.categories||[]).includes(c))&&(!l||(x.levels||[]).includes(l))});grid.innerHTML=filtered.map(card).join('');count.textContent=filtered.length===suppliers.length?`Showing all ${suppliers.length} listings`:`${filtered.length} listing${filtered.length===1?'':'s'} found`;empty.style.display=filtered.length?'none':'block'}
search.addEventListener('input',apply);[region,category,level].forEach(x=>x.addEventListener('change',apply));form.addEventListener('submit',e=>{e.preventDefault();apply();$('directory').scrollIntoView({behavior:'smooth',block:'start'})});clear.addEventListener('click',()=>{search.value=region.value=category.value=level.value='';apply();window.scrollTo({top:0,behavior:'smooth'});search.focus({preventScroll:true})});
const supplierForm=$('supplier-form');if(supplierForm)supplierForm.addEventListener('submit',async e=>{e.preventDefault();const b=supplierForm.querySelector('[type=submit]'),old=b.textContent;b.disabled=true;b.textContent='Submitting…';try{const res=await fetch('https://formspree.io/f/xpqnynqe',{method:'POST',body:new FormData(supplierForm),headers:{Accept:'application/json'}});if(!res.ok)throw new Error();supplierForm.style.display='none';$('submission-success').style.display='block'}catch(err){alert('Something went wrong. Please try again.');b.disabled=false;b.textContent=old}});
const schema=document.createElement('script');schema.type='application/ld+json';schema.textContent=JSON.stringify({'@context':'https://schema.org','@type':'ItemList',name:"The Baker's Directory listings",numberOfItems:suppliers.length,itemListElement:suppliers.map((x,i)=>({'@type':'ListItem',position:i+1,item:{'@type':'Organization',name:x.name,url:x.website,areaServed:x.region,description:x.description}}))});document.head.appendChild(schema);apply();